os:
  - linux

language: node_js

node_js:
  - lts/*
  - stable

script:
  - npm run lint
  - npm run test-travis

after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls

matrix:
  include:
    - node_js: stable
      dist: trusty
      addons:
        chrome: stable
        firefox: latest
      script:
        - npm run test-e2e Chrome_travis_ci
        - npm run test-e2e Firefox
      after_script: # 删除之前配置
